services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80" # Expose only Caddy on port 80 (removed from web)
    volumes:
      - ./caddy:/etc/caddy
    networks:
      - nook-net

  web:
    image: node:20-alpine
    volumes:
      - ./web:/app
    working_dir: /app
    ports:
      - "5173:5173"
    networks:
      - nook-net
    command: ["sh", "-c", "npm install && npm run dev"]

  catalog:
    image: node:20-alpine
    volumes:
      - ./catalog:/app
    working_dir: /app
    command: ["npm", "run", "start:dev"]
    networks:
      - nook-net
    depends_on:
      - kafka
      - db

    environment:
      DB_HOST: catalog_db
      DB_PORT: 3306
      DB_NAME: catalog_db
      DB_USER: catalog_user
      DB_PASSWORD: catalog_pass

  inventory:
    image: node:20-alpine
    volumes:
      - ./inventory:/app
    working_dir: /app
    command: ["npm", "run", "start:dev"]
    networks:
      - nook-net
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:4003"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_STANDBY_REPLICAS: 1
      KAFKA_CONTROLLED_SHUTDOWN_ENABLE: "true"
    volumes:
      - "kafka_data:/var/lib/kafka/data"
      - "kafka_secrets:/var/lib/kafka/secrets"
    ports:
      - "4002:9093"
    networks:
      - nook-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: "4003"
    volumes:
      - "zookeeper_data:/var/lib/zookeeper/data"
      - "zookeeper_logs:/var/lib/zookeeper/logs"
      - "zookeeper_secrets:/var/lib/zookeeper/secrets"
    networks:
      - nook-net

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "5001:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:4003
    networks:
      - nook-net
    depends_on:
      - kafka

  db:
    image: mysql:8.0
    container_name: catalog_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: catalog_db
      MYSQL_USER: catalog_user
      MYSQL_PASSWORD: catalog_pass
    ports:
      - "3306:3306"
    volumes:
      - catalog_db:/var/lib/mysql
    networks:
      - nook-net

volumes:
  kafka_data:
  kafka_secrets:
  zookeeper_data:
  zookeeper_logs:
  zookeeper_secrets:
  catalog_db:

networks:
  nook-net:
    driver: bridge
