export type PlantSize = {
  id: number;
  catalogId: number;
  size: string;
  height: string;
  price: number;
};

export const plantSizes: PlantSize[] = [
  {
    size: 'Small',
    price: 15.99,
    height: '6-10 inches',
    catalogId: 1,
    id: 1,
  },
  {
    size: 'Medium',
    price: 25.99,
    height: '12-18 inches',
    catalogId: 1,
    id: 2,
  },
  {
    size: 'Large',
    price: 39.99,
    height: '24-30 inches',
    catalogId: 1,
    id: 3,
  },
  {
    size: 'Small',
    price: 9.99,
    height: '8-12 inches',
    catalogId: 2,
    id: 4,
  },
  {
    size: 'Medium',
    price: 14.99,
    height: '14-18 inches',
    catalogId: 2,
    id: 5,
  },
  {
    size: 'Medium',
    price: 12.99,
    height: '10-15 inches',
    catalogId: 3,
    id: 6,
  },
  {
    size: 'Large',
    price: 22.99,
    height: '20-24 inches',
    catalogId: 3,
    id: 7,
  },
  {
    size: 'Small',
    price: 10.99,
    height: '6-8 inches',
    catalogId: 4,
    id: 8,
  },
  {
    size: 'Medium',
    price: 18.99,
    height: '10-12 inches',
    catalogId: 4,
    id: 9,
  },
  {
    size: 'Medium',
    price: 24.99,
    height: '14-20 inches',
    catalogId: 5,
    id: 10,
  },
  {
    size: 'Large',
    price: 45.99,
    height: '30-36 inches',
    catalogId: 5,
    id: 11,
  },
  {
    size: 'Medium',
    price: 34.99,
    height: '18-24 inches',
    catalogId: 6,
    id: 12,
  },
  {
    size: 'Large',
    price: 64.99,
    height: '36-48 inches',
    catalogId: 6,
    id: 13,
  },
  {
    size: 'Small',
    price: 8.99,
    height: '6-8 inches',
    catalogId: 7,
    id: 14,
  },
  {
    size: 'Hanging Basket',
    price: 16.99,
    height: '10-12 inches',
    catalogId: 7,
    id: 15,
  },
  {
    size: 'Small',
    price: 19.99,
    height: '8-12 inches',
    catalogId: 8,
    id: 16,
  },
  {
    size: 'Medium',
    price: 29.99,
    height: '16-20 inches',
    catalogId: 8,
    id: 17,
  },
  {
    size: 'Small',
    price: 16.99,
    height: '8-12 inches',
    catalogId: 9,
    id: 18,
  },
  {
    size: 'Hanging Basket',
    price: 22.99,
    height: '12-16 inches',
    catalogId: 9,
    id: 19,
  },
  {
    size: 'Medium',
    price: 13.99,
    height: '12-18 inches',
    catalogId: 10,
    id: 20,
  },
  {
    size: 'Hanging Basket',
    price: 19.99,
    height: '18-24 inches',
    catalogId: 10,
    id: 21,
  },
  {
    size: 'Medium',
    price: 22.99,
    height: '16-20 inches',
    catalogId: 11,
    id: 22,
  },
  {
    size: 'Large',
    price: 49.99,
    height: '30-36 inches',
    catalogId: 11,
    id: 23,
  },
  {
    size: 'Small',
    price: 14.99,
    height: '4-6 inches',
    catalogId: 12,
    id: 24,
  },
  {
    size: 'Medium',
    price: 24.99,
    height: '8-12 inches',
    catalogId: 12,
    id: 25,
  },
  {
    size: 'Small',
    price: 18.99,
    height: '10-12 inches',
    catalogId: 13,
    id: 26,
  },
  {
    size: 'Medium',
    price: 28.99,
    height: '14-18 inches',
    catalogId: 13,
    id: 27,
  },
  {
    size: 'Small',
    price: 12.99,
    height: '6-8 inches',
    catalogId: 14,
    id: 28,
  },
  {
    size: 'Medium',
    price: 19.99,
    height: '10-14 inches',
    catalogId: 14,
    id: 29,
  },
  {
    size: 'Small',
    price: 14.99,
    height: '8-12 inches',
    catalogId: 15,
    id: 30,
  },
  {
    size: 'Medium',
    price: 24.99,
    height: '14-20 inches',
    catalogId: 15,
    id: 31,
  },
  {
    size: 'Medium',
    price: 29.99,
    height: '18-24 inches',
    catalogId: 16,
    id: 32,
  },
  {
    size: 'Large',
    price: 59.99,
    height: '36-48 inches',
    catalogId: 16,
    id: 33,
  },
  {
    size: 'Small',
    price: 17.99,
    height: '12-16 inches',
    catalogId: 17,
    id: 34,
  },
  {
    size: 'Medium',
    price: 29.99,
    height: '18-24 inches',
    catalogId: 17,
    id: 35,
  },
  {
    size: 'Large',
    price: 49.99,
    height: '30-36 inches',
    catalogId: 17,
    id: 36,
  },
  {
    size: 'Medium',
    price: 24.99,
    height: '20-24 inches',
    catalogId: 18,
    id: 37,
  },
  {
    size: 'Large',
    price: 44.99,
    height: '36-48 inches',
    catalogId: 18,
    id: 38,
  },
  {
    size: 'Small',
    price: 8.99,
    height: '4-6 inches',
    catalogId: 19,
    id: 39,
  },
  {
    size: 'Medium',
    price: 14.99,
    height: '8-12 inches',
    catalogId: 19,
    id: 40,
  },
  {
    size: 'Small',
    price: 6.99,
    height: '2-4 inches',
    catalogId: 20,
    id: 41,
  },
  {
    size: 'Medium',
    price: 11.99,
    height: '4-6 inches',
    catalogId: 20,
    id: 42,
  },
  {
    size: 'Medium',
    price: 11.99,
    height: '12-18 inches',
    catalogId: 21,
    id: 43,
  },
  {
    size: 'Large',
    price: 24.99,
    height: '20-24 inches',
    catalogId: 21,
    id: 44,
  },
  {
    size: 'Small',
    price: 7.99,
    height: '4-6 inches',
    catalogId: 22,
    id: 45,
  },
  {
    size: 'Medium',
    price: 13.99,
    height: '6-8 inches',
    catalogId: 22,
    id: 46,
  },
  {
    size: 'Small',
    price: 12.99,
    height: '8-12 inches',
    catalogId: 23,
    id: 47,
  },
  {
    size: 'Medium',
    price: 19.99,
    height: '14-18 inches',
    catalogId: 23,
    id: 48,
  },
  {
    size: 'Small',
    price: 6.99,
    height: '3-5 inches',
    catalogId: 24,
    id: 49,
  },
  {
    size: 'Medium',
    price: 11.99,
    height: '6-8 inches',
    catalogId: 24,
    id: 50,
  },
  {
    size: 'Small',
    price: 5.99,
    height: '2-4 inches',
    catalogId: 25,
    id: 51,
  },
  {
    size: 'Medium',
    price: 10.99,
    height: '5-7 inches',
    catalogId: 25,
    id: 52,
  },
  {
    size: 'Small',
    price: 7.99,
    height: '4-6 inches',
    catalogId: 26,
    id: 53,
  },
  {
    size: 'Medium',
    price: 12.99,
    height: '8-10 inches',
    catalogId: 26,
    id: 54,
  },
  {
    size: 'Small',
    price: 8.99,
    height: '6-8 inches',
    catalogId: 27,
    id: 55,
  },
  {
    size: 'Medium',
    price: 14.99,
    height: '10-12 inches',
    catalogId: 27,
    id: 56,
  },
  {
    size: 'Small',
    price: 9.99,
    height: '4-6 inches',
    catalogId: 28,
    id: 57,
  },
  {
    size: 'Medium',
    price: 15.99,
    height: '8-10 inches',
    catalogId: 28,
    id: 58,
  },
  {
    size: 'Small',
    price: 5.99,
    height: '3-5 inches',
    catalogId: 29,
    id: 59,
  },
  {
    size: 'Medium',
    price: 9.99,
    height: '6-8 inches',
    catalogId: 29,
    id: 60,
  },
  {
    size: 'Small',
    price: 7.99,
    height: '6-8 inches',
    catalogId: 30,
    id: 61,
  },
  {
    size: 'Medium',
    price: 12.99,
    height: '10-14 inches',
    catalogId: 30,
    id: 62,
  },
  {
    size: 'Small',
    price: 8.99,
    height: '4-6 inches',
    catalogId: 31,
    id: 63,
  },
  {
    size: 'Medium',
    price: 13.99,
    height: '8-12 inches',
    catalogId: 31,
    id: 64,
  },
  {
    size: 'Small',
    price: 6.99,
    height: '4-6 inches',
    catalogId: 32,
    id: 65,
  },
  {
    size: 'Medium',
    price: 11.99,
    height: '7-10 inches',
    catalogId: 32,
    id: 66,
  },
  {
    size: 'Small',
    price: 9.99,
    height: '4-6 inches',
    catalogId: 33,
    id: 67,
  },
  {
    size: 'Medium',
    price: 14.99,
    height: '8-12 inches',
    catalogId: 33,
    id: 68,
  },
  {
    size: 'Small',
    price: 7.99,
    height: '2-4 inches',
    catalogId: 34,
    id: 69,
  },
  {
    size: 'Medium',
    price: 12.99,
    height: '5-7 inches',
    catalogId: 34,
    id: 70,
  },
  {
    size: 'Small',
    price: 8.99,
    height: '3-5 inches',
    catalogId: 35,
    id: 71,
  },
  {
    size: 'Medium',
    price: 13.99,
    height: '6-8 inches',
    catalogId: 35,
    id: 72,
  },
  {
    size: 'Small',
    price: 7.99,
    height: '1-2 inches',
    catalogId: 36,
    id: 73,
  },
  {
    size: 'Medium',
    price: 11.99,
    height: '2-3 inches',
    catalogId: 36,
    id: 74,
  },
  {
    size: 'Small',
    price: 6.99,
    height: '4-6 inches',
    catalogId: 37,
    id: 75,
  },
  {
    size: 'Medium',
    price: 12.99,
    height: '8-12 inches',
    catalogId: 37,
    id: 76,
  },
  {
    size: 'Small',
    price: 7.99,
    height: '4-6 inches',
    catalogId: 38,
    id: 77,
  },
  {
    size: 'Medium',
    price: 12.99,
    height: '6-10 inches',
    catalogId: 38,
    id: 78,
  },
  {
    size: 'Small',
    price: 9.99,
    height: '6-8 inches',
    catalogId: 39,
    id: 79,
  },
  {
    size: 'Medium',
    price: 14.99,
    height: '10-12 inches',
    catalogId: 39,
    id: 80,
  },
  {
    size: 'Small',
    price: 8.99,
    height: '4-6 inches',
    catalogId: 40,
    id: 81,
  },
  {
    size: 'Medium',
    price: 13.99,
    height: '6-10 inches',
    catalogId: 40,
    id: 82,
  },
  {
    size: 'Small',
    price: 7.99,
    height: '3-5 inches',
    catalogId: 41,
    id: 83,
  },
  {
    size: 'Medium',
    price: 12.99,
    height: '5-8 inches',
    catalogId: 41,
    id: 84,
  },
  {
    size: 'Small',
    price: 8.99,
    height: '4-6 inches',
    catalogId: 42,
    id: 85,
  },
  {
    size: 'Medium',
    price: 13.99,
    height: '8-10 inches',
    catalogId: 42,
    id: 86,
  },
  {
    size: 'Small',
    price: 8.99,
    height: '4-6 inches',
    catalogId: 43,
    id: 87,
  },
  {
    size: 'Medium',
    price: 13.99,
    height: '8-12 inches',
    catalogId: 43,
    id: 88,
  },
  {
    size: 'Small',
    price: 7.99,
    height: '3-5 inches',
    catalogId: 44,
    id: 89,
  },
  {
    size: 'Medium',
    price: 12.99,
    height: '5-8 inches',
    catalogId: 44,
    id: 90,
  },
];
